[project]
name = "MLOps_course_AGH_lab_02"
version = "1.0.0"
description = ""
readme = "README.md"

requires-python = "==3.11.*"

dependencies = [
    "apache-airflow-providers-amazon[s3fs]>=9.20.0",
    "apache-airflow[celery,postgres,standard,uv]==3.1.5",
    "joblib>=1.5.3",
    "polars>=1.37.1",
    "pyarrow",
    "s3fs>=2026.1.0",
    "scikit-learn>=1.8.0",
]

[dependency-groups]
dev = [
    "ruff"
]

airflow_common = [
    "apache-airflow[celery,postgres,standard,uv]==3.1.5",
    "requests",
    "twelvedata",
    "s3fs>=2026.1.0",
    "polars>=1.37.1",
    "joblib>=1.5.3",
    "scikit-learn>=1.8.0",
]
